name: Generate 3D Profile

on:
  schedule:
    - cron: "0 0 * * 0,3"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d
    steps:
      - uses: actions/checkout@v6
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: sangammagariaravind123
      - name: update 3d-contrib
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "update: user info"; then
            git push
          fi
